version: '3.7'

services:
  api:
    image: ghcr.io/guan840912/flask-uploadfile/flask-uploadfile:latest
    container_name: python-flask
    privileged: true
    ports:
      - "8080:8080"
    volumes:
      - $HOME/flask-uploadfile-pic:/app/pic:Z
