name:  workflow for Codecov
on:
  push:
    tags:
      - v1*
jobs:
  codecov:
    runs-on: ubuntu-latest
    env:
      PYTHON: '3.7'
    steps:
    - uses: actions/checkout@v1
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.7
    - name: Generate coverage report
      run: |
        pip install pytest
        pip install pytest-cov
        pytest tests.py --cov=./ --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: unittests